name: Create a PR to upgrade the crate to a new version

# Manually dispatch this action from the Actions page
on:
  workflow_dispatch:
    inputs:
      prev_version:
        description: 'Upgrading from version'
        required: true
        type: string
      next_version:
        description: 'Upgrading to version'
        required: true
        type: string

jobs:
  print-versions:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo and install dependencies
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.15
      - name: Install wit-bindgen
        shell: bash
        run: cargo binstall wit-bindgen-cli
      - name: Install wit-deps
        shell: bash
        run: cargo binstall wit-deps-cli

      # echo input
      - name: Print the versions
        run: echo Upgrading from ${{ inputs.prev_version }} to ${{ inputs.next_version }} 

      # upgrade
      - name: Upgrade tag
        run:  find . -type f -name "*.wit" -print0 | xargs -0 sed -i '' -e 's/@0\.2\.1/@0\.2\.2/g'
      - name: Upgrade wit deps
        run:  wit-deps update
      - name: Generate markdown
        run:  wit-bindgen markdown wit --html-in-md --all-features

      # file PR
      - name: create pull request
        run: gh pr create -B main -H v${{ inputs.next_version }} --title 'Upgrade to ${{ inputs.next_version }}' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
